config/routes.rb
Rails.application.routes.draw do

  resources :inquiries

  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  devise_for :admins
  resources :arts
	root 'static#home'
	get 'static/developer', page: "developer"
	get 'static/game', page: "game"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	mount_uploader :art, ArtUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :authenticate_admin!, only: [ :show ,:edit, :update, :destroy, :new]
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:title, :author, :art)
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  def inquiry_landing
    
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to root_url, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:first_name, :last_name, :contact, :email, :address)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

	def home
		
	end

	def developer
		
	end

	def game
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/arts/_form.html.erb
<%= form_for(art) do |f| %>
  <% if art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_area :author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
  <div id="particles-js"> 
  </div>
 <section class=" art-header">  
 <%= render partial: "shared/head"%>
</section>

<div class="container art-container"> 
 <% @arts.each_slice(12).to_a.each do |art| %>
 <div class="row ">
  <% art.each do |art| %>
  <div class="col-md-2 art-box" >
    <%= link_to image_tag(art.art_url(:thumb).to_s), art.art_url, target: :_blank %>
    <div class="title" > <%= art.title %></div>
    <div class="author"> <%= art.author %></div>
  </div>  
  <% end -%>
</div>
<% end %>
</div>




<%= render partial: "shared/footer"%>




<!-- <p id="notice"><%= notice %></p>

<h1>Arts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td><%= art.title %></td>
        <td><%= art.author %></td>
        <td><%= link_to 'Show', art %></td>
        <td><%= link_to 'Edit', edit_art_path(art) %></td>
        <td><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Art', new_art_path %>
 -->

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form', art: @art %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @art.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @art.author %>
</p>

<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>

app/views/inquiries/_form.html.erb
<div id="particles-js"> 
</div>

<div class="fixed-background">
  <%= render partial: "shared/head"%>
</div>

<div class="container-fluid inquiry" align="center">


  <%= form_for(inquiry) do |f| %>
  <% if inquiry.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

    <ul>
      <% inquiry.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6"><%= f.text_area :first_name, placeholder: "First Name" , class: 'first_name',:required => true %>      
    </div>

    <div class="col-sm-6"> <%= f.text_area :email, placeholder: "E-mail Address" , class: 'email',:required => true %> 
    </div>

  </div>

  <div class="row">
   <div class="col-sm-6"><%= f.text_area :last_name, placeholder: "Last Name" , class: 'last_name',:required => true %></div>
    <div class="col-sm-6"> 
    <%= f.text_area :address, placeholder: "Address" , class: 'address',:required => true %>
  </div>
 </div>


 <div class="row">
   <div class="col-sm-6"> <%= f.text_area :contact , placeholder: "Contact Number" , class: 'contact_number',:required => true%> </div>
   
 </div>


 <div class="row"> 
 
  <div class="col-sm-12"><%= f.submit "COLLABORATE", class: "inquiry-btn" %> 

  </div>



</div>


<% end %>

</div>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.first_name %></td>
        <td><%= inquiry.last_name %></td>
        <td><%= inquiry.contact %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.address %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<%= render 'form', inquiry: @inquiry %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @inquiry.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @inquiry.last_name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @inquiry.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @inquiry.address %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcidGamesEntertainment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "particles"%>
  <%= javascript_include_tag "app"%>
  </body>
</html>

app/views/shared/_footer.html.erb
      <footer>
        <div class="container-fluid">






          <div class=" footer-title" align="center">
        <button type="button" class="browse-games "> <%= link_to "COLLABORATE", new_inquiry_path , {:style=>'color:#FFFFFF;'}%></button>


          <h1 style="color: white;" > LETS CREATE SOMETHING TOGETHER</h1> </div>
          <div class=" col-sm-12 footer-title2"> <h1 align="center" style="color: white;"> We love new IDEAS! got some? </h1></div>



        </div>



        <section class="footer-nav">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-4 footer-about" >
                <ul>
                  <h1>ABOUT</h1>
                  <li><%= link_to "Home", root_path %></li>
                  <li><a href="#">About Us</a></li>
                  <li><%= link_to "Developers", static_developer_path%></li>
                  <li><%= link_to "Collaborate", new_inquiry_path %> </li>
                </ul>
              </div>

              <div class="col-sm-4 footer-gamenart">
                <ul>
                  <h1> GAMES AND ARTS</h1>
                  <li> <%= link_to "Game Development", static_game_path %> </li>
                  <li> <a href="#"> 3D Graphics</a></li>
                  <li> <%= link_to "Graphic Arts", arts_path %> </li>
                </ul>
              </div>

              <div class="col-sm-4 footer-mobilenweb" >
                <ul>
                  <h1>MOBILE AND WEB </h1>
                  <li> <a href="#"> Web Development</a></li>
                  <li> <a href="#"> Android Development</a></li>
                  <li> <a href="#"> iOS Development</a></li>
                </ul>
              </div>

              <!-- <div class="col-sm-3 footer-blog">
                <ul>
                  <h1> BLOGS</h1>
                  <li> <a href="#"> Design</a></li>
                  <li> <a href="#">Games</a></li>
                  <li> <a href="#"> 3D</a></li>
                  <li> <a href="#"> Technology</a></li>
                  <li> <a href="#"> Web Development</a></li>
                  <li> <a href="#"> Mobile App Development</a></li>
                </ul>
              </div> -->
            </div>
          </div>
        </section>

        <div class="container footer-logo">
          <%= image_tag("agelogo.png", class: "footer-age-logo") %>

          <p style="color: white; text-align: center; margin-top: 10px; padding-bottom: 100px;">© Acid Games Entertainment Ltd 2017</p>
        </div>


      </footer>

app/views/shared/_head.html.erb
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
          </div>
          <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav navbar-center">
              <li role="presentation"><%= link_to "HOME", root_path %> </li>
              <li role="presentation"><a href="#">MOBILE</a></li>
              <li role="presentation"><a href="#">WEB</a></li>
              <li role="presentation"><%= link_to "GAMES", static_game_path %></li>
              <li role="presentation"><%= link_to "GRAPHICS", arts_path %></li>
              <!-- <li role="presentation"><a href="#">BLOGS</a></li> -->
            </ul>
          </div>
        </div>
      </nav>